/* PET (B1 Preliminary) 單詞庫 — 依主題分類
   w: 英文  z: 中文  p: 詞性  c: 分類  ex: 例句 */
(function (global) {
  'use strict';

  var CATEGORIES = [
    { id: 'daily',   name: '日常生活', icon: '🏠' },
    { id: 'school',  name: '學校教育', icon: '🎒' },
    { id: 'work',    name: '工作職業', icon: '💼' },
    { id: 'travel',  name: '旅遊交通', icon: '✈️' },
    { id: 'food',    name: '食物飲食', icon: '🍜' },
    { id: 'health',  name: '健康身體', icon: '💊' },
    { id: 'nature',  name: '環境自然', icon: '🌳' },
    { id: 'tech',    name: '科技媒體', icon: '💻' },
    { id: 'feeling', name: '情緒個性', icon: '🙂' },
    { id: 'verb',    name: '常用動詞', icon: '⚡' },
    { id: 'adj',     name: '常用形容詞', icon: '🎨' },
    { id: 'link',    name: '連接與副詞', icon: '🔗' }
  ];

  var WORDS = [
    // ---------- 日常生活 ----------
    { w: 'neighbour',    z: '鄰居',        p: 'n.',   c: 'daily', ex: 'My neighbour helps me look after the cat.' },
    { w: 'furniture',    z: '家具',        p: 'n.',   c: 'daily', ex: 'We bought some furniture for the new flat.' },
    { w: 'cupboard',     z: '櫥櫃',        p: 'n.',   c: 'daily', ex: 'The plates are in the cupboard.' },
    { w: 'blanket',      z: '毯子',        p: 'n.',   c: 'daily', ex: 'She put a warm blanket on the bed.' },
    { w: 'rubbish',      z: '垃圾',        p: 'n.',   c: 'daily', ex: 'Please take the rubbish outside.' },
    { w: 'housework',    z: '家務',        p: 'n.',   c: 'daily', ex: 'We share the housework every weekend.' },
    { w: 'wallet',       z: '皮夾',        p: 'n.',   c: 'daily', ex: 'He left his wallet on the table.' },
    { w: 'key',          z: '鑰匙',        p: 'n.',   c: 'daily', ex: 'I cannot find my house key.' },
    { w: 'towel',        z: '毛巾',        p: 'n.',   c: 'daily', ex: 'Take a clean towel from the shelf.' },
    { w: 'shelf',        z: '架子',        p: 'n.',   c: 'daily', ex: 'The books are on the top shelf.' },
    { w: 'stairs',       z: '樓梯',        p: 'n.',   c: 'daily', ex: 'Be careful on the stairs.' },
    { w: 'balcony',      z: '陽台',        p: 'n.',   c: 'daily', ex: 'We have breakfast on the balcony.' },
    { w: 'washing machine', z: '洗衣機',   p: 'n.',   c: 'daily', ex: 'The washing machine is broken again.' },
    { w: 'bill',         z: '帳單',        p: 'n.',   c: 'daily', ex: 'The electricity bill arrived this morning.' },
    { w: 'discount',     z: '折扣',        p: 'n.',   c: 'daily', ex: 'Students get a 10% discount.' },
    { w: 'receipt',      z: '收據',        p: 'n.',   c: 'daily', ex: 'Keep the receipt in case you return it.' },
    { w: 'customer',     z: '顧客',        p: 'n.',   c: 'daily', ex: 'The shop was full of customers.' },
    { w: 'queue',        z: '排隊；隊伍',  p: 'n./v.', c: 'daily', ex: 'We had to queue for twenty minutes.' },
    { w: 'borrow',       z: '借入',        p: 'v.',   c: 'daily', ex: 'Can I borrow your umbrella?' },
    { w: 'lend',         z: '借出',        p: 'v.',   c: 'daily', ex: 'She lent me her bike for the day.' },

    // ---------- 學校教育 ----------
    { w: 'subject',      z: '科目',        p: 'n.',   c: 'school', ex: 'Science is my favourite subject.' },
    { w: 'homework',     z: '家庭作業',    p: 'n.',   c: 'school', ex: 'I finished my homework before dinner.' },
    { w: 'exam',         z: '考試',        p: 'n.',   c: 'school', ex: 'The exam lasts two hours.' },
    { w: 'revise',       z: '複習',        p: 'v.',   c: 'school', ex: 'I need to revise for the test.' },
    { w: 'notes',        z: '筆記',        p: 'n.',   c: 'school', ex: 'She takes good notes in class.' },
    { w: 'timetable',    z: '課表；時刻表', p: 'n.',  c: 'school', ex: 'Check the timetable for Monday.' },
    { w: 'term',         z: '學期',        p: 'n.',   c: 'school', ex: 'The new term starts in September.' },
    { w: 'degree',       z: '學位',        p: 'n.',   c: 'school', ex: 'He has a degree in history.' },
    { w: 'progress',     z: '進步',        p: 'n.',   c: 'school', ex: 'You have made good progress this year.' },
    { w: 'mistake',      z: '錯誤',        p: 'n.',   c: 'school', ex: 'Everyone makes mistakes when learning.' },
    { w: 'explain',      z: '解釋',        p: 'v.',   c: 'school', ex: 'Can you explain this word to me?' },
    { w: 'translate',    z: '翻譯',        p: 'v.',   c: 'school', ex: 'Translate the sentence into English.' },
    { w: 'pronounce',    z: '發音',        p: 'v.',   c: 'school', ex: 'How do you pronounce this name?' },
    { w: 'practise',     z: '練習',        p: 'v.',   c: 'school', ex: 'You should practise speaking every day.' },
    { w: 'memorise',     z: '背誦；記住',  p: 'v.',   c: 'school', ex: 'Do not just memorise the words.' },
    { w: 'dictionary',   z: '字典',        p: 'n.',   c: 'school', ex: 'Look it up in the dictionary.' },
    { w: 'library',      z: '圖書館',      p: 'n.',   c: 'school', ex: 'The library closes at nine.' },
    { w: 'classmate',    z: '同學',        p: 'n.',   c: 'school', ex: 'My classmates are very friendly.' },
    { w: 'uniform',      z: '制服',        p: 'n.',   c: 'school', ex: 'We wear a uniform at school.' },
    { w: 'certificate',  z: '證書',        p: 'n.',   c: 'school', ex: 'You will receive a certificate after the course.' },

    // ---------- 工作職業 ----------
    { w: 'employer',     z: '雇主',        p: 'n.',   c: 'work', ex: 'Her employer gave her an extra day off.' },
    { w: 'employee',     z: '員工',        p: 'n.',   c: 'work', ex: 'The company has 200 employees.' },
    { w: 'interview',    z: '面試',        p: 'n./v.', c: 'work', ex: 'I have a job interview on Friday.' },
    { w: 'salary',       z: '薪水',        p: 'n.',   c: 'work', ex: 'The salary is paid every month.' },
    { w: 'colleague',    z: '同事',        p: 'n.',   c: 'work', ex: 'My colleagues are easy to work with.' },
    { w: 'meeting',      z: '會議',        p: 'n.',   c: 'work', ex: 'The meeting starts at ten.' },
    { w: 'deadline',     z: '截止期限',    p: 'n.',   c: 'work', ex: 'The deadline is next Tuesday.' },
    { w: 'experience',   z: '經驗',        p: 'n.',   c: 'work', ex: 'She has five years of experience.' },
    { w: 'apply',        z: '申請',        p: 'v.',   c: 'work', ex: 'I applied for a summer job.' },
    { w: 'earn',         z: '賺取',        p: 'v.',   c: 'work', ex: 'He earns enough to travel.' },
    { w: 'manage',       z: '管理；設法做到', p: 'v.', c: 'work', ex: 'She manages a small team.' },
    { w: 'engineer',     z: '工程師',      p: 'n.',   c: 'work', ex: 'My sister is a software engineer.' },
    { w: 'nurse',        z: '護理師',      p: 'n.',   c: 'work', ex: 'The nurse checked my temperature.' },
    { w: 'lawyer',       z: '律師',        p: 'n.',   c: 'work', ex: 'You should talk to a lawyer.' },
    { w: 'chef',         z: '主廚',        p: 'n.',   c: 'work', ex: 'The chef made a special dessert.' },
    { w: 'shift',        z: '輪班',        p: 'n.',   c: 'work', ex: 'He works the night shift.' },
    { w: 'part-time',    z: '兼職的',      p: 'adj.', c: 'work', ex: 'She has a part-time job at a café.' },
    { w: 'retire',       z: '退休',        p: 'v.',   c: 'work', ex: 'My father retired last year.' },
    { w: 'overtime',     z: '加班',        p: 'n.',   c: 'work', ex: 'He worked overtime to finish the report.' },
    { w: 'career',       z: '職業生涯',    p: 'n.',   c: 'work', ex: 'He wants a career in music.' },

    // ---------- 旅遊交通 ----------
    { w: 'journey',      z: '旅程',        p: 'n.',   c: 'travel', ex: 'The journey takes about three hours.' },
    { w: 'luggage',      z: '行李',        p: 'n.',   c: 'travel', ex: 'Leave your luggage at the hotel.' },
    { w: 'passport',     z: '護照',        p: 'n.',   c: 'travel', ex: 'Do not forget your passport.' },
    { w: 'ticket',       z: '車票；門票',  p: 'n.',   c: 'travel', ex: 'I bought a return ticket.' },
    { w: 'platform',     z: '月台',        p: 'n.',   c: 'travel', ex: 'The train leaves from platform 4.' },
    { w: 'flight',       z: '航班',        p: 'n.',   c: 'travel', ex: 'Our flight was delayed by an hour.' },
    { w: 'delay',        z: '延誤',        p: 'n./v.', c: 'travel', ex: 'There was a long delay at the airport.' },
    { w: 'abroad',       z: '在國外',      p: 'adv.', c: 'travel', ex: 'They are studying abroad this year.' },
    { w: 'accommodation', z: '住宿',       p: 'n.',   c: 'travel', ex: 'The price includes accommodation.' },
    { w: 'book',         z: '預訂',        p: 'v.',   c: 'travel', ex: 'We booked a room online.' },
    { w: 'tourist',      z: '觀光客',      p: 'n.',   c: 'travel', ex: 'The old town is full of tourists.' },
    { w: 'guide',        z: '導遊；指南',  p: 'n.',   c: 'travel', ex: 'The guide showed us the castle.' },
    { w: 'map',          z: '地圖',        p: 'n.',   c: 'travel', ex: 'I downloaded a map of the city.' },
    { w: 'traffic',      z: '交通；車流',  p: 'n.',   c: 'travel', ex: 'The traffic was terrible this morning.' },
    { w: 'rush hour',    z: '尖峰時段',    p: 'n.',   c: 'travel', ex: 'Avoid travelling during rush hour.' },
    { w: 'coach',        z: '長途巴士',    p: 'n.',   c: 'travel', ex: 'We went to London by coach.' },
    { w: 'ferry',        z: '渡輪',        p: 'n.',   c: 'travel', ex: 'The ferry crosses the river every hour.' },
    { w: 'destination',  z: '目的地',      p: 'n.',   c: 'travel', ex: 'Our final destination was the beach.' },
    { w: 'suitcase',     z: '行李箱',      p: 'n.',   c: 'travel', ex: 'My suitcase is too heavy.' },
    { w: 'view',         z: '景色',        p: 'n.',   c: 'travel', ex: 'The room has a lovely view of the sea.' },

    // ---------- 食物飲食 ----------
    { w: 'recipe',       z: '食譜',        p: 'n.',   c: 'food', ex: 'This recipe is easy to follow.' },
    { w: 'ingredient',   z: '食材',        p: 'n.',   c: 'food', ex: 'Mix all the ingredients in a bowl.' },
    { w: 'vegetable',    z: '蔬菜',        p: 'n.',   c: 'food', ex: 'Eat more fresh vegetables.' },
    { w: 'dessert',      z: '甜點',        p: 'n.',   c: 'food', ex: 'We had ice cream for dessert.' },
    { w: 'snack',        z: '點心',        p: 'n.',   c: 'food', ex: 'I had a quick snack before class.' },
    { w: 'meal',         z: '一餐',        p: 'n.',   c: 'food', ex: 'Dinner is the main meal of the day.' },
    { w: 'boil',         z: '煮沸',        p: 'v.',   c: 'food', ex: 'Boil the water for five minutes.' },
    { w: 'fry',          z: '油炸；煎',    p: 'v.',   c: 'food', ex: 'Fry the onions until they are soft.' },
    { w: 'bake',         z: '烘烤',        p: 'v.',   c: 'food', ex: 'She baked a cake for my birthday.' },
    { w: 'taste',        z: '嚐起來；味道', p: 'v./n.', c: 'food', ex: 'This soup tastes delicious.' },
    { w: 'delicious',    z: '美味的',      p: 'adj.', c: 'food', ex: 'The noodles were absolutely delicious.' },
    { w: 'menu',         z: '菜單',        p: 'n.',   c: 'food', ex: 'Can we see the menu, please?' },
    { w: 'order',        z: '點餐；訂購',  p: 'v./n.', c: 'food', ex: 'I ordered a salad and a juice.' },
    { w: 'waiter',       z: '服務生',      p: 'n.',   c: 'food', ex: 'The waiter brought us some water.' },
    { w: 'vegetarian',   z: '素食者；素食的', p: 'n./adj.', c: 'food', ex: 'My brother is a vegetarian.' },
    { w: 'flavour',      z: '風味',        p: 'n.',   c: 'food', ex: 'This tea has a strong flavour.' },
    { w: 'fresh',        z: '新鮮的',      p: 'adj.', c: 'food', ex: 'We bought fresh bread this morning.' },
    { w: 'thirsty',      z: '口渴的',      p: 'adj.', c: 'food', ex: 'I am thirsty after running.' },
    { w: 'sour',         z: '酸的',        p: 'adj.', c: 'food', ex: 'The lemon is very sour.' },
    { w: 'plate',        z: '盤子',        p: 'n.',   c: 'food', ex: 'Put the cake on a small plate.' },

    // ---------- 健康身體 ----------
    { w: 'headache',     z: '頭痛',        p: 'n.',   c: 'health', ex: 'I have a bad headache today.' },
    { w: 'medicine',     z: '藥',          p: 'n.',   c: 'health', ex: 'Take this medicine twice a day.' },
    { w: 'injury',       z: '受傷',        p: 'n.',   c: 'health', ex: 'He missed the game because of an injury.' },
    { w: 'treatment',    z: '治療',        p: 'n.',   c: 'health', ex: 'The treatment lasted two weeks.' },
    { w: 'appointment',  z: '預約',        p: 'n.',   c: 'health', ex: 'I made an appointment with the dentist.' },
    { w: 'exercise',     z: '運動；練習',  p: 'n./v.', c: 'health', ex: 'Regular exercise keeps you healthy.' },
    { w: 'breathe',      z: '呼吸',        p: 'v.',   c: 'health', ex: 'Breathe slowly and relax.' },
    { w: 'recover',      z: '康復',        p: 'v.',   c: 'health', ex: 'She recovered quickly after the operation.' },
    { w: 'ill',          z: '生病的',      p: 'adj.', c: 'health', ex: 'He felt ill after the trip.' },
    { w: 'painful',      z: '疼痛的',      p: 'adj.', c: 'health', ex: 'My knee is still painful.' },
    { w: 'fit',          z: '健康的；合身', p: 'adj.', c: 'health', ex: 'Cycling keeps me fit.' },
    { w: 'diet',         z: '飲食',        p: 'n.',   c: 'health', ex: 'A balanced diet is important.' },
    { w: 'shoulder',     z: '肩膀',        p: 'n.',   c: 'health', ex: 'He hurt his left shoulder.' },
    { w: 'stomach',      z: '胃；肚子',    p: 'n.',   c: 'health', ex: 'My stomach hurts a little.' },
    { w: 'temperature',  z: '體溫；溫度',  p: 'n.',   c: 'health', ex: 'The nurse took my temperature.' },
    { w: 'chemist',      z: '藥局；藥劑師', p: 'n.',  c: 'health', ex: 'You can buy it at the chemist.' },
    { w: 'ambulance',    z: '救護車',      p: 'n.',   c: 'health', ex: 'Someone called an ambulance.' },
    { w: 'operation',    z: '手術',        p: 'n.',   c: 'health', ex: 'The operation went well.' },
    { w: 'sleepy',       z: '想睡的',      p: 'adj.', c: 'health', ex: 'I feel sleepy after lunch.' },
    { w: 'relax',        z: '放鬆',        p: 'v.',   c: 'health', ex: 'Music helps me relax.' },

    // ---------- 環境自然 ----------
    { w: 'environment',  z: '環境',        p: 'n.',   c: 'nature', ex: 'We must protect the environment.' },
    { w: 'pollution',    z: '污染',        p: 'n.',   c: 'nature', ex: 'Air pollution is a serious problem.' },
    { w: 'recycle',      z: '回收',        p: 'v.',   c: 'nature', ex: 'We recycle paper and glass.' },
    { w: 'climate',      z: '氣候',        p: 'n.',   c: 'nature', ex: 'The climate here is quite dry.' },
    { w: 'forest',       z: '森林',        p: 'n.',   c: 'nature', ex: 'We walked through the forest.' },
    { w: 'island',       z: '島嶼',        p: 'n.',   c: 'nature', ex: 'They live on a small island.' },
    { w: 'desert',       z: '沙漠',        p: 'n.',   c: 'nature', ex: 'It almost never rains in the desert.' },
    { w: 'weather',      z: '天氣',        p: 'n.',   c: 'nature', ex: 'The weather changed suddenly.' },
    { w: 'thunder',      z: '雷',          p: 'n.',   c: 'nature', ex: 'We heard thunder in the distance.' },
    { w: 'flood',        z: '水災',        p: 'n.',   c: 'nature', ex: 'The flood damaged many houses.' },
    { w: 'earthquake',   z: '地震',        p: 'n.',   c: 'nature', ex: 'The earthquake lasted ten seconds.' },
    { w: 'energy',       z: '能源；活力',  p: 'n.',   c: 'nature', ex: 'Solar energy is clean and cheap.' },
    { w: 'waste',        z: '浪費；廢棄物', p: 'v./n.', c: 'nature', ex: 'Do not waste water.' },
    { w: 'wildlife',     z: '野生動物',    p: 'n.',   c: 'nature', ex: 'The park protects local wildlife.' },
    { w: 'plant',        z: '植物；種植',  p: 'n./v.', c: 'nature', ex: 'They planted trees along the road.' },
    { w: 'countryside',  z: '鄉間',        p: 'n.',   c: 'nature', ex: 'We spent the weekend in the countryside.' },
    { w: 'valley',       z: '山谷',        p: 'n.',   c: 'nature', ex: 'A small river runs through the valley.' },
    { w: 'sunrise',      z: '日出',        p: 'n.',   c: 'nature', ex: 'We got up early to watch the sunrise.' },
    { w: 'seaside',      z: '海邊',        p: 'n.',   c: 'nature', ex: 'We spend every summer at the seaside.' },
    { w: 'protect',      z: '保護',        p: 'v.',   c: 'nature', ex: 'We should protect the oceans.' },

    // ---------- 科技媒體 ----------
    { w: 'screen',       z: '螢幕',        p: 'n.',   c: 'tech', ex: 'The screen is too bright.' },
    { w: 'download',     z: '下載',        p: 'v.',   c: 'tech', ex: 'You can download the app for free.' },
    { w: 'upload',       z: '上傳',        p: 'v.',   c: 'tech', ex: 'She uploaded the photos yesterday.' },
    { w: 'password',     z: '密碼',        p: 'n.',   c: 'tech', ex: 'I forgot my password again.' },
    { w: 'device',       z: '裝置',        p: 'n.',   c: 'tech', ex: 'The game works on any device.' },
    { w: 'network',      z: '網路',        p: 'n.',   c: 'tech', ex: 'The network is very slow today.' },
    { w: 'offline',      z: '離線的',      p: 'adj.', c: 'tech', ex: 'You can still play offline.' },
    { w: 'connect',      z: '連線；連接',  p: 'v.',   c: 'tech', ex: 'Connect your phone to the printer.' },
    { w: 'message',      z: '訊息',        p: 'n.',   c: 'tech', ex: 'I sent you a message this morning.' },
    { w: 'website',      z: '網站',        p: 'n.',   c: 'tech', ex: 'Their website is easy to use.' },
    { w: 'search',       z: '搜尋',        p: 'v./n.', c: 'tech', ex: 'Search for the word online.' },
    { w: 'battery',      z: '電池',        p: 'n.',   c: 'tech', ex: 'My battery is almost flat.' },
    { w: 'charger',      z: '充電器',      p: 'n.',   c: 'tech', ex: 'Can I borrow your charger?' },
    { w: 'headphones',   z: '耳機',        p: 'n.',   c: 'tech', ex: 'He wore headphones on the bus.' },
    { w: 'advertisement', z: '廣告',       p: 'n.',   c: 'tech', ex: 'I saw an advertisement for the concert.' },
    { w: 'channel',      z: '頻道',        p: 'n.',   c: 'tech', ex: 'There is a film on channel five.' },
    { w: 'programme',    z: '節目',        p: 'n.',   c: 'tech', ex: 'It is my favourite TV programme.' },
    { w: 'keyboard',     z: '鍵盤',        p: 'n.',   c: 'tech', ex: 'The keyboard stopped working.' },
    { w: 'software',     z: '軟體',        p: 'n.',   c: 'tech', ex: 'We need to update the software.' },
    { w: 'invention',    z: '發明',        p: 'n.',   c: 'tech', ex: 'The phone was a great invention.' },

    // ---------- 情緒個性 ----------
    { w: 'confident',    z: '有自信的',    p: 'adj.', c: 'feeling', ex: 'She feels confident about the exam.' },
    { w: 'nervous',      z: '緊張的',      p: 'adj.', c: 'feeling', ex: 'I was nervous before the interview.' },
    { w: 'patient',      z: '有耐心的',    p: 'adj.', c: 'feeling', ex: 'Be patient with your little brother.' },
    { w: 'polite',       z: '有禮貌的',    p: 'adj.', c: 'feeling', ex: 'He is always polite to customers.' },
    { w: 'generous',     z: '慷慨的',      p: 'adj.', c: 'feeling', ex: 'It was generous of you to pay.' },
    { w: 'honest',       z: '誠實的',      p: 'adj.', c: 'feeling', ex: 'Please give me an honest answer.' },
    { w: 'lazy',         z: '懶惰的',      p: 'adj.', c: 'feeling', ex: 'I felt lazy on Sunday morning.' },
    { w: 'proud',        z: '驕傲的',      p: 'adj.', c: 'feeling', ex: 'Her parents are proud of her.' },
    { w: 'shy',          z: '害羞的',      p: 'adj.', c: 'feeling', ex: 'He is too shy to speak in class.' },
    { w: 'curious',      z: '好奇的',      p: 'adj.', c: 'feeling', ex: 'Children are naturally curious.' },
    { w: 'disappointed', z: '失望的',      p: 'adj.', c: 'feeling', ex: 'I was disappointed with the film.' },
    { w: 'surprised',    z: '驚訝的',      p: 'adj.', c: 'feeling', ex: 'We were surprised by the news.' },
    { w: 'worried',      z: '擔心的',      p: 'adj.', c: 'feeling', ex: 'She is worried about her results.' },
    { w: 'cheerful',     z: '開朗的',      p: 'adj.', c: 'feeling', ex: 'He gave me a cheerful smile.' },
    { w: 'annoyed',      z: '惱怒的',      p: 'adj.', c: 'feeling', ex: 'I was annoyed by the noise.' },
    { w: 'brave',        z: '勇敢的',      p: 'adj.', c: 'feeling', ex: 'It was brave of her to speak up.' },
    { w: 'friendly',     z: '友善的',      p: 'adj.', c: 'feeling', ex: 'The staff were very friendly.' },
    { w: 'serious',      z: '嚴肅的；嚴重的', p: 'adj.', c: 'feeling', ex: 'This is a serious problem.' },
    { w: 'sense of humour', z: '幽默感',   p: 'n.',   c: 'feeling', ex: 'She has a great sense of humour.' },
    { w: 'attitude',     z: '態度',        p: 'n.',   c: 'feeling', ex: 'He has a positive attitude to work.' },

    // ---------- 常用動詞 ----------
    { w: 'achieve',      z: '達成',        p: 'v.',   c: 'verb', ex: 'She achieved her goal in one year.' },
    { w: 'admit',        z: '承認',        p: 'v.',   c: 'verb', ex: 'He admitted that he was wrong.' },
    { w: 'avoid',        z: '避免',        p: 'v.',   c: 'verb', ex: 'Try to avoid sugary drinks.' },
    { w: 'complain',     z: '抱怨',        p: 'v.',   c: 'verb', ex: 'They complained about the service.' },
    { w: 'describe',     z: '描述',        p: 'v.',   c: 'verb', ex: 'Describe the picture in detail.' },
    { w: 'discover',     z: '發現',        p: 'v.',   c: 'verb', ex: 'We discovered a small café nearby.' },
    { w: 'encourage',    z: '鼓勵',        p: 'v.',   c: 'verb', ex: 'My teacher encouraged me to try.' },
    { w: 'improve',      z: '改善',        p: 'v.',   c: 'verb', ex: 'Reading improves your vocabulary.' },
    { w: 'invite',       z: '邀請',        p: 'v.',   c: 'verb', ex: 'They invited us to the party.' },
    { w: 'prefer',       z: '偏好',        p: 'v.',   c: 'verb', ex: 'I prefer tea to coffee.' },
    { w: 'prepare',      z: '準備',        p: 'v.',   c: 'verb', ex: 'We prepared dinner together.' },
    { w: 'realise',      z: '意識到',      p: 'v.',   c: 'verb', ex: 'I did not realise it was so late.' },
    { w: 'suggest',      z: '建議',        p: 'v.',   c: 'verb', ex: 'He suggested going by train.' },
    { w: 'promise',      z: '承諾',        p: 'v./n.', c: 'verb', ex: 'She promised to call me back.' },
    { w: 'repair',       z: '修理',        p: 'v.',   c: 'verb', ex: 'Can you repair my bike?' },
    { w: 'refuse',       z: '拒絕',        p: 'v.',   c: 'verb', ex: 'He refused to answer the question.' },
    { w: 'compare',      z: '比較',        p: 'v.',   c: 'verb', ex: 'Compare the two photos carefully.' },
    { w: 'decide',       z: '決定',        p: 'v.',   c: 'verb', ex: 'We decided to stay at home.' },
    { w: 'arrange',      z: '安排',        p: 'v.',   c: 'verb', ex: 'I arranged a meeting for Monday.' },
    { w: 'celebrate',    z: '慶祝',        p: 'v.',   c: 'verb', ex: 'They celebrated their anniversary.' },

    // ---------- 常用形容詞 ----------
    { w: 'available',    z: '可得到的',    p: 'adj.', c: 'adj', ex: 'Tickets are available online.' },
    { w: 'comfortable',  z: '舒適的',      p: 'adj.', c: 'adj', ex: 'These shoes are very comfortable.' },
    { w: 'crowded',      z: '擁擠的',      p: 'adj.', c: 'adj', ex: 'The train was crowded this morning.' },
    { w: 'difficult',    z: '困難的',      p: 'adj.', c: 'adj', ex: 'The second question was difficult.' },
    { w: 'expensive',    z: '昂貴的',      p: 'adj.', c: 'adj', ex: 'That jacket is too expensive.' },
    { w: 'famous',       z: '著名的',      p: 'adj.', c: 'adj', ex: 'The city is famous for its bridges.' },
    { w: 'modern',       z: '現代的',      p: 'adj.', c: 'adj', ex: 'They live in a modern flat.' },
    { w: 'ordinary',     z: '普通的',      p: 'adj.', c: 'adj', ex: 'It was an ordinary Tuesday.' },
    { w: 'quiet',        z: '安靜的',      p: 'adj.', c: 'adj', ex: 'We found a quiet corner to study.' },
    { w: 'similar',      z: '相似的',      p: 'adj.', c: 'adj', ex: 'The two words have similar meanings.' },
    { w: 'useful',       z: '有用的',      p: 'adj.', c: 'adj', ex: 'This app is really useful.' },
    { w: 'common',       z: '常見的',      p: 'adj.', c: 'adj', ex: 'This is a common mistake.' },
    { w: 'empty',        z: '空的',        p: 'adj.', c: 'adj', ex: 'The street was completely empty.' },
    { w: 'heavy',        z: '重的',        p: 'adj.', c: 'adj', ex: 'My bag is too heavy to carry.' },
    { w: 'careful',      z: '小心的',      p: 'adj.', c: 'adj', ex: 'Be careful with the hot water.' },
    { w: 'boring',       z: '無聊的',      p: 'adj.', c: 'adj', ex: 'The lesson was a bit boring.' },
    { w: 'dangerous',    z: '危險的',      p: 'adj.', c: 'adj', ex: 'It is dangerous to cycle at night.' },
    { w: 'lucky',        z: '幸運的',      p: 'adj.', c: 'adj', ex: 'You are lucky to live near the sea.' },
    { w: 'perfect',      z: '完美的',      p: 'adj.', c: 'adj', ex: 'The weather was perfect for a picnic.' },
    { w: 'traditional',  z: '傳統的',      p: 'adj.', c: 'adj', ex: 'We tried some traditional food.' },

    // ---------- 連接與副詞 ----------
    { w: 'although',     z: '雖然',        p: 'conj.', c: 'link', ex: 'Although it rained, we enjoyed it.' },
    { w: 'however',      z: '然而',        p: 'adv.', c: 'link', ex: 'It was cold; however, we went out.' },
    { w: 'because of',   z: '因為（後接名詞）', p: 'prep.', c: 'link', ex: 'We stayed in because of the rain.' },
    { w: 'in order to',  z: '為了',        p: 'phr.', c: 'link', ex: 'She left early in order to catch the bus.' },
    { w: 'therefore',    z: '因此',        p: 'adv.', c: 'link', ex: 'It was late; therefore we took a taxi.' },
    { w: 'instead of',   z: '而不是',      p: 'prep.', c: 'link', ex: 'Take the bus instead of a taxi.' },
    { w: 'as well as',   z: '除了…也',    p: 'phr.', c: 'link', ex: 'She speaks French as well as English.' },
    { w: 'unless',       z: '除非',        p: 'conj.', c: 'link', ex: 'We will go unless it rains.' },
    { w: 'while',        z: '當…的時候',  p: 'conj.', c: 'link', ex: 'He called while I was cooking.' },
    { w: 'finally',      z: '最後',        p: 'adv.', c: 'link', ex: 'Finally, add the salt.' },
    { w: 'immediately',  z: '立刻',        p: 'adv.', c: 'link', ex: 'Call me immediately after the test.' },
    { w: 'probably',     z: '可能',        p: 'adv.', c: 'link', ex: 'She will probably arrive late.' },
    { w: 'hardly',       z: '幾乎不',      p: 'adv.', c: 'link', ex: 'I could hardly hear him.' },
    { w: 'especially',   z: '尤其',        p: 'adv.', c: 'link', ex: 'I like fruit, especially mangoes.' },
    { w: 'recently',     z: '最近',        p: 'adv.', c: 'link', ex: 'We recently moved to a new house.' },
    { w: 'suddenly',     z: '突然',        p: 'adv.', c: 'link', ex: 'Suddenly the lights went out.' },
    { w: 'usually',      z: '通常',        p: 'adv.', c: 'link', ex: 'I usually walk to school.' },
    { w: 'nearly',       z: '幾乎',        p: 'adv.', c: 'link', ex: 'It is nearly nine o\'clock.' },
    { w: 'at least',     z: '至少',        p: 'phr.', c: 'link', ex: 'Practise at least ten minutes a day.' },
    { w: 'by the way',   z: '順帶一提',    p: 'phr.', c: 'link', ex: 'By the way, did you call her?' }
  ];

  global.PET_DATA = { CATEGORIES: CATEGORIES, WORDS: WORDS };
})(this);
